### ISSUE TITLE
Refreshing the page still throws a 404 error in the console.

### ISSUE THREAD

**Issue by harvanchik** [rafrex/spa-github-pages#47] opened 2021-03-30 04:55 UTC
While the page does still load, a 404 error is still thrown in the console, and on some browsers, a banner is displayed at the top of the page saying that the page could not be found.

**Comment by rafgraph** [comment] 2021-03-30 14:24
Yeah it’ll be 404 followed by a 200. That’s how it works, see the readme for details. I haven’t seen the banner you referred to, which browsers do that?

**Comment by harvanchik** [comment] 2021-03-30 17:04
Brave browser does that. Even though the 200 follows, the banner persists. Now, there is a setting to disable it, but I think it's enabled by default.

**Comment by rafgraph** [comment] 2021-03-30 17:32
Okay good to know. I'm going to close this issue as it is working as intended. Ideally GitHub pages would natively support spas, but that is not the case which is why this workaround exists. Some alternatives are to use a static site generator with GitHub pages (e.g. Gatsby), or to host your site somewhere that natively supports spas (e.g. Netlify).

**Closed as completed by rafgraph** 2021-03-30 17:32 UTC
